apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: eingaruca/nodejs:v1 
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-svc
spec:
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 3000